// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpzyCmfQJtbfTi1PrUwTwMh7t4WHj-YOQ',
    appId: '1:787608161079:web:81a9e257adf9b5f9cba8b2',
    messagingSenderId: '787608161079',
    projectId: 'app-1920',
    authDomain: 'app-1920.firebaseapp.com',
    storageBucket: 'app-1920.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFS3h2IcgRR9q4RJ8HCx9wBLoJKFK9Knc',
    appId: '1:787608161079:android:e5a234071eafe557cba8b2',
    messagingSenderId: '787608161079',
    projectId: 'app-1920',
    storageBucket: 'app-1920.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNIn4nWdtIZT4mYI8sMRrLbe8696Whaag',
    appId: '1:787608161079:ios:dabce48246857cd2cba8b2',
    messagingSenderId: '787608161079',
    projectId: 'app-1920',
    storageBucket: 'app-1920.firebasestorage.app',
    iosBundleId: 'com.example.app89',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpzyCmfQJtbfTi1PrUwTwMh7t4WHj-YOQ',
    appId: '1:787608161079:web:b138ab9490e59fdbcba8b2',
    messagingSenderId: '787608161079',
    projectId: 'app-1920',
    authDomain: 'app-1920.firebaseapp.com',
    storageBucket: 'app-1920.firebasestorage.app',
  );
}
